version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: dockertest/application:latest
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app