name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Build Docker image
      run: docker build -t apptest-docker .

    - name: Push Docker image to registry
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag apptest-docker ${{ secrets.DOCKER_USERNAME }}/apptest-docker
        docker push ${{ secrets.DOCKER_USERNAME }}/apptest-docker

    - name: Grant Docker permissions
      run: |
        sudo usermod -aG docker $USER
        newgrp docker
      if: runner.os == 'Linux'

    - name: Configure SSH known_hosts
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H 43.203.19.149 >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -i ~/.ssh/id_rsa ubuntu@43.203.19.149 'bash -s' < deploy.sh
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        CONTAINER_NAME: mycontainer
        IMAGE_NAME: apptest-docker

    - name: Restart Nginx
      run: |
        sudo systemctl restart nginx.service
